# TEST FLEET - Docker Compose only for testing 
# You can test environments and stuff

version: '2'

volumes:
  settings:                          # Only required if using PERSISTENT flag (see below)

services:

  browser:
    build: .
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)

  sut:
    build: sut
    network_mode: host
    restart: no
    depends_on:
      - browser